# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Golden-file tests: run every analyzer against the synthetic sample fixture
and assert the finding counts and statuses match the committed golden output.

The fixture lives in ``tests/fixtures/sample/raw`` (fully synthetic, generated by
``tests/build_fixture.py``) and the golden expectations in
``tests/fixtures/sample/golden`` (regenerate with ``python -m tests.gen_golden``).

The comparison contract is the (rule_id, dimension, status) projection — stable
against evidence-text wording changes but sensitive to any count or status flip.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

import pytest

from tests._analyzers import (
    ANALYZERS,
    FIXTURE_RAW,
    GOLDEN_DIR,
    projection,
    run_analyzer,
)

# Expected per-analyzer finding counts (frozen from the sample fixture).
EXPECTED_COUNTS: Dict[str, int] = {
    "findings_tenant_settings": 7,
    "findings_architecture": 14,
    "findings_performance": 12,
    "findings_storage_mode": 4,
    "findings_governance": 9,
    "findings_operational_excellence": 3,
    "findings_security": 9,
    "findings_cost": 7,
    "findings_notebook_code": 6,
    "findings_best_practices": 7,
}
EXPECTED_TOTAL = sum(EXPECTED_COUNTS.values())  # 71


def _load_golden(basename: str) -> List[Dict[str, Any]]:
    path = GOLDEN_DIR / f"{basename}.json"
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def test_fixture_present() -> None:
    assert FIXTURE_RAW.is_dir(), f"missing fixture dir: {FIXTURE_RAW}"
    raw_files = list(FIXTURE_RAW.glob("*.json"))
    assert len(raw_files) >= 14, f"expected the full raw shape, got {len(raw_files)} files"


def test_golden_present() -> None:
    for basename in ANALYZERS.values():
        assert (GOLDEN_DIR / f"{basename}.json").is_file(), (
            f"missing golden {basename}.json — run `python -m tests.gen_golden`"
        )


@pytest.mark.parametrize("module_name", list(ANALYZERS))
def test_analyzer_has_cli_entrypoint(module_name: str) -> None:
    """Each analyzer must expose a callable ``main``.

    The Fabric ``02_Analyze`` notebook runs every analyzer as a subprocess
    (``python -m analyzers.<name>``), which executes the ``__main__`` block and
    calls ``main()``. A missing ``def main`` raises ``NameError`` at runtime and
    silently drops that whole dimension's findings — invisible to the other
    tests, which call ``analyze()`` directly.
    """
    import importlib

    module = importlib.import_module(module_name)
    assert callable(getattr(module, "main", None)), (
        f"{module_name} has no callable main() — `python -m {module_name}` would "
        f"crash and write no findings"
    )


@pytest.mark.parametrize(("module_name", "basename"), list(ANALYZERS.items()))
def test_analyzer_matches_golden(module_name: str, basename: str) -> None:
    findings = run_analyzer(module_name)
    golden = _load_golden(basename)

    # 1) count contract
    assert len(findings) == EXPECTED_COUNTS[basename], (
        f"{basename}: expected {EXPECTED_COUNTS[basename]} findings, got {len(findings)}"
    )

    # 2) (rule_id, dimension, status) projection matches golden exactly
    assert projection(findings) == projection(golden), (
        f"{basename}: rule/status projection drifted from golden — "
        f"re-run `python -m tests.gen_golden` if the change is intended"
    )


@pytest.mark.parametrize(("module_name", "basename"), list(ANALYZERS.items()))
def test_finding_shape(module_name: str, basename: str) -> None:
    """Every finding must carry the fields the report renderer relies on."""
    required = {"rule_id", "dimension", "status", "title"}
    valid_status = {"pass", "fail", "info"}
    for f in run_analyzer(module_name):
        missing = required - f.keys()
        assert not missing, f"{basename}: finding missing fields {missing}: {f}"
        assert f["status"] in valid_status, f"{basename}: bad status {f['status']!r}"


def test_total_finding_count() -> None:
    total = sum(len(run_analyzer(m)) for m in ANALYZERS)
    assert total == EXPECTED_TOTAL, f"expected {EXPECTED_TOTAL} findings total, got {total}"
